// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKHzBVZ-kU2OOdepdlH97icQ9fXNt0Xw8',
    appId: '1:742136489088:web:59893db320601fed0eb265',
    messagingSenderId: '742136489088',
    projectId: 'mbank-login',
    authDomain: 'mbank-login.firebaseapp.com',
    storageBucket: 'mbank-login.appspot.com',
    measurementId: 'G-1VLDBW13R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHt4gNURDLdjIq_FC9MHR2roz9lN6hgoc',
    appId: '1:742136489088:android:2fe5a5b2f16503ce0eb265',
    messagingSenderId: '742136489088',
    projectId: 'mbank-login',
    storageBucket: 'mbank-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLzlaTiMCmXGJAdML0MCobuy3bbRsZpnQ',
    appId: '1:742136489088:ios:f1310f13b82cfb940eb265',
    messagingSenderId: '742136489088',
    projectId: 'mbank-login',
    storageBucket: 'mbank-login.appspot.com',
    iosBundleId: 'com.example.utsMobileprog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLzlaTiMCmXGJAdML0MCobuy3bbRsZpnQ',
    appId: '1:742136489088:ios:6d3a399306cec8920eb265',
    messagingSenderId: '742136489088',
    projectId: 'mbank-login',
    storageBucket: 'mbank-login.appspot.com',
    iosBundleId: 'com.example.utsMobileprog.RunnerTests',
  );
}
